version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    restart: always
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
